# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8840d5638cd5b10b6df3842341056eeeb32c769c4a80cb202823d566451dfaf9f06516443aa8c198377181458f4275e3b03a658bf3e402dbfcde0311dc31cf14

test:
  secret_key_base: 5bbb85e219133a1cbc98d2789ae8a845417c8bfdac7fdac04b106c6cfb938f4e87d67c0f16803001b84f73301c9840b824f8ada3cbbccd12ec096c4f94d34373

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
